language: android

android:
  jdk:
    - oraclejdk8
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository

script:
   - ./gradlew clean build --stacktrace
