language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository

script:
   - ./gradlew clean build --stacktrace
